src/Entity/Animal.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\AnimalRepository")
 */
class Animal
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @var string
     * @ORM\Column(type="string", length=50)
     */
    private $nome;

    /**
     * @var string
     * @ORM\Column(type="date")
     */
    private $data_nascimento;

    /**
     * @var object
     * @ORM\ManyToMany(targetEntity="App\Entity\Cliente", mappedBy="animal")
     */
    private $cliente;

    /**
     * @var object
     * @ORM\ManyToOne(targetEntity="App\Entity\Raca", inversedBy="id")
     */
    private $raca;

    public function getId()
    {
        return $this->id;
    }

    /**
     * @return string
     */
    public function getNome(): ?string
    {
        return $this->nome;
    }

    /**
     * @param string $nome
     * @return Animal
     */
    public function setNome(string $nome): Animal
    {
        $this->nome = $nome;
        return $this;
    }

    /**
     * @return string
     */
    public function getDataNascimento()
    {
        return $this->data_nascimento;
    }

    /**
     * @param string $data_nascimento
     * @return Animal
     */
    public function setDataNascimento($data_nascimento): Animal
    {
        $this->data_nascimento = $data_nascimento;
        return $this;
    }

    /**
     * @return object
     */
    public function getCliente()
    {
        return $this->cliente;
    }

    /**
     * @param object $cliente
     * @return Animal
     */
    public function setCliente($cliente): Animal
    {
        $this->cliente = $cliente;
        return $this;
    }

    /**
     * @return object
     */
    public function getRaca()
    {
        return $this->raca;
    }

    /**
     * @param object $raca
     * @return Animal
     */
    public function setRaca($raca): Animal
    {
        $this->raca = $raca;
        return $this;
    }
}

src/Controller/AnimaisController.php
<?php

namespace App\Controller;

use App\Entity\Animal;
use App\Form\AnimalType;
use Sensio\Bundle\FrameworkExtraBundle\Configuration\Template;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;

class AnimaisController extends Controller
{
    /**
     * @Route("/animais", name="animais_index")
     * @Template("animais/index.html.twig")
     */
    public function index()
    {
        $entityManager = $this->getDoctrine()->getManager();
        $animais = $entityManager->getRepository(Animal::class)->findAll();

        return [
            'animais' => $animais
        ];
    }

    /**
     * @Route("animais/view/{id}", name="animais_view")
     * @Template("animais/view.html.twig")
     */
    public function view(Animal $animal)
    {
        return [
            'animal' => $animal
        ];
    }

    /**
     * @param Request $request
     * @Route("animais/create", name="animais_create")
     * @Template("animais/create.html.twig")
     * @return array|\Symfony\Component\HttpFoundation\RedirectResponse
     */
    public function create(Request $request)
    {
        $animal = new Animal;
        $form = $this->createForm(AnimalType::class, $animal);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager = $this->getDoctrine()->getManager();
            $entityManager->persist($animal);
            $entityManager->flush();

            $this->addFlash('success', 'Animal cadastrado com sucesso!');

            return $this->redirectToRoute('animais_index');
        }

        return [
            'form' => $form->createView()
        ];
    }
}

templates/animais/create.html.twig
{% extends 'base.html.twig' %}

{% block title %}Cadastrar Animais{% endblock %}

{% block body %}
    <h1>Cadastrar Animal</h1>
    <hr />
    {{ form(form) }}
{% endblock %}

templates/animais/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Consulta de Animais{% endblock %}

{% block body %}
    <h1>Consulta de Animais</h1>
    <hr />

    <div class="row">
        <div class="col-md-12 form-group">
            <a href="{{ path('animais_create') }}" class="btn btn-primary pull-right">Novo Animal</a>
        </div>
    </div>

    <table class="table table-hover table-striped">
        <thead>
            <tr>
                <th>ID</th>
                <th>Nome</th>
                <th>Data Nasc.</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
        {% for animal in animais %}
            <tr>
                <td>{{ animal.id }}</td>
                <td>
                    <a href="{{ path('animais_view', {'id': animal.id}) }}" title="Visualizar detalhes deste registro">
                        {{ animal.nome }}
                    </a>
                </td>
                <td>{{ animal.dataNascimento|date('d/m/Y') }}</td>
                <td>

                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="4" class="text-center">Nenhum registro encontrado.</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/animais/view.html.twig
{% extends 'base.html.twig' %}

{% block title %}Visualização de Animais{% endblock %}

{% block body %}
    <h1>Visualizando Animal <small>{{ animal.nome }}</small></h1>
    <hr />

    <table class="table table-striped">
        <tbody>
            <tr>
                <th>ID</th>
                <td>{{ animal.id }}</td>
            </tr>
            <tr>
                <th>Nome</th>
                <td>{{ animal.nome }}</td>
            </tr>
            <tr>
                <th>Data de Nascimento</th>
                <td>{{ animal.dataNascimento|date('d/m/Y') }}</td>
            </tr>
            <tr>
                <th colspan="2" class="text-center"><h3>Proprietários</h3></th>
            </tr>
            <tr>
                <td>
                    <ul>
                        {% for cliente in animal.cliente %}
                            <li><a href="{{ path('clientes_view', {id: cliente.id}) }}">{{ cliente.nome }}</a></li>
                        {% else %}
                            <li>Nenhum proprietário para este cliente.</li>
                        {% endfor %}
                    </ul>
                </td>
            </tr>
        </tbody>
    </table>

{% endblock %}